:Author: DocQuantik
:Email: {w.magrini@yahoo.fr}
:Date: 15/04/2019
:Revision: version#1.0
:License: Public Domain

= Project: Arduino Control Board

Describe your project

== Step 1: Installation
To install this project, you just have to assemble the circuit and upload the code as described in the next parts.

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── SerialControlAnalogOutput.ino       => main Arduino file
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a GNU GPL License.

=== Contributing
To contribute to this project please contact DocQuantik https://id.arduino.cc/DocQuantik

=== BOM
This is the material list needed for the project

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===

