:Author: DocQuantik
:Email: {w.magrini@yahoo.fr}
:Date: 15/04/2019
:Revision: version#1.0
:License: Public Domain

= Project: Arduino Control Board

Describe your project

== Step 1: Installation
To install this project, you just have to assemble the circuit and upload the code as described in the next parts.

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 SerialControlAnalogOutput                => Arduino sketch folder
  ├── SerialControlAnalogOutput.ino       => main Arduino file
  ├── layout.png          => an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a GNU GPLv3 License.

=== Contributing
To contribute to this project please contact DocQuantik https://id.arduino.cc/DocQuantik

=== BOM
This is the material list needed for the project

|===
| ID | Part name                | Part number | Quantity
| R1 | 470 Resistor             |             | 6
| C1 | 10 uF Capacitor          |             | 3
| R2 | 5k Adjustable resistor   |             | 3
| AO1 | Dual channel op-amp     | LM358N      | 2
| B1 | Female BNC connector     |             | 6
| A1 | Arduino UNO              | A000066     | 1
|===

